# Generated by Django 5.0.4 on 2024-04-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemPedidos',
            new_name='ItemPedido',
        ),
        migrations.RenameModel(
            old_name='Pedidos',
            new_name='Pedido',
        ),
    ]
